# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: corey schaf
description: "Software Engineer.  AI Engineer.  Game Developer"
keywords: "backend, ai, ml, engineer, software engineer, code, senior, unreal, unity"
url: https://coreyjs.dev
baseurl: ""

google_analytics: UA-177184589-1
repo: https://github.com/coreyjs/coreyjs.github.io

# Author settings
author:
  name: Corey Schaf
  job: Software Engineer.  AI Engineer.  Game Developer
  bio: "A sr software engineer who loves developing server side tech that powers API's and user experiences. I am currently studying machine learning and AI to better understand the data all around us."
  thumb: /images/author.jpeg
  email: coreyjs@hey.com
  url: https://coreyjs.dev/
  github: https://github.com/coreyjs
  twitter: https://twitter.com/corey_s_
  linkedin: https://linkedin.com/in/cschaf

# navbar pages
navbar:
  - slug: about
    title: About

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
